### ISSUE TITLE
StableDiffusion example pycuda._driver.LogicError

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [geohot/tinygrad#1013]
I got following error when I tried to run stable diffusion example:

```
Traceback (most recent call last):
  File "/home/sher/Dev/tinygrad/examples/stable_diffusion.py", line 684, in <module>
    dat = (x.detach().numpy().clip(0, 1)*255).astype(np.uint8)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/tensor.py", line 111, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/lazy.py", line 194, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/lazy.py", line 163, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/ops.py", line 166, in exec_ast
    prg.exec(k.bufs)
  File "/home/sher/Dev/tinygrad/tinygrad/ops.py", line 95, in exec
    return self(rawbufs)
           ^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/ops.py", line 99, in __call__
    if et := self.clprg(self.global_size, self.local_size, *rawbufs, wait=force_wait or DEBUG>=1): GlobalCounters.time_sum_s += et
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/tinygrad/tinygrad/runtime/ops_cuda.py", line 41, in __call__
    self.prg(*[x._buf for x in args], block=tuple(local_size), grid=tuple(global_size))
  File "/home/sher/.local/lib/python3.11/site-packages/pycuda/driver.py", line 502, in function_call
    func._launch_kernel(grid, block, arg_buf, shared, None)
pycuda._driver.LogicError: cuLaunchKernel failed: invalid argument
```

Here is my GPU spec.
![image](https://github.com/geohot/tinygrad/assets/45091811/2da5415d-4d1a-4cb9-8e39-84ff7a50e611)

Any clues what might went wrong?

**Comment by python273** [comment]
There's a bug. Seems like `global_size` is too big? `(3, 262144, 1)`

**Comment by python273** [comment]
works with `OPTLOCAL=2`, but might be slow on the first run?

**Comment by python273** [comment]
Seems fixed with the last commit

**Comment by geohot** [comment]
Yea, should be fixed
