### ISSUE TITLE
lr tensor shape mismatch when GPU is on

### ISSUE THREAD

**Issue by zhenyulin** [geohot/tinygrad#138]
```python
# %%
from tinygrad.tensor import Tensor
from tinygrad.utils import layer_init_uniform
from tinygrad.optim import SGD

from pprint import pprint


class MLP:
    def __init__(
        self,
        input_size,
        network_size,
        gpu=True,
        learning_rate=0.001,
    ):
        self.gpu = gpu
        self.input_size = input_size
        self.network_size = network_size

        layer_sizes = zip([input_size, *network_size[:-1]], network_size)

        self.layers = [
            Tensor(layer_init_uniform(in_size, out_size), gpu=self.gpu)
            for (in_size, out_size) in layer_sizes
        ]
        self.optimizer = SGD(self.layers, lr=learning_rate)

    def __call__(self, x):
        output = Tensor(x, gpu=self.gpu)
        for i, layer in enumerate(self.layers):
            output = output.dot(layer)
            if i != len(self.layers) - 1:
                output = output.relu()
        return output

    def learn(self, x, y):

        _y = Tensor(y, gpu=self.gpu)
        two = Tensor([[2]], gpu=self.gpu)

        output = self.__call__(x)
        loss = (output - _y).pow(two).mean()

        loss.backward()
        # self.optimizer.step()


mlp = MLP(3, [2, 1], gpu=True)

x = [[1.0, 1.0, 1.0]]
y = [[1.0]]


mlp.learn(x, y)
# pprint([layer for layer in mlp.layers])

for layer in mlp.optimizer.params:
    print(layer.grad)
    print((layer.grad * Tensor([[0.01]], gpu=True)).cpu())
    print((layer.grad * mlp.optimizer.lr).cpu())

```

```python
print((layer.grad * Tensor([[0.01]], gpu=True)).cpu())
```
print out the grad right to me
```
Tensor array([[ 0.        , -0.00866722],
       [ 0.        , -0.00866722],
       [ 0.        , -0.00866722]], dtype=float32) with grad None
```

while

```python
print((layer.grad * mlp.optimizer.lr).cpu())
```
reports 
```
shape mismatch in binop a*b: (3, 2) (1,)
```
if GPU is off, there's no this issue.

Not sure if there's something I've missed here?

**Comment by Liamdoult** [comment]
I was able to replicate this on the latest `PyPi` release:
```
Tensor <pyopencl._cl.Buffer object at 0x7fb7ea1014f0> with grad None
Tensor array([[0.        , 0.01043132],
       [0.        , 0.01043132],
       [0.        , 0.01043132]], dtype=float32) with grad None
Traceback (most recent call last):
  File "test_mlp.py", line 60, in <module>
    print((layer.grad * mlp.optimizer.lr).cpu())
  File "/home/liam/Documents/oss/env/lib/python3.8/site-packages/tinygrad/tensor.py", line 187, in dispatch
    return f.apply(f, self, *x, **kwargs)
  File "/home/liam/Documents/oss/env/lib/python3.8/site-packages/tinygrad/tensor.py", line 175, in apply
    ret = Tensor(op.forward(ctx, *[t.data for t in x], **kwargs))
  File "/home/liam/Documents/oss/env/lib/python3.8/site-packages/tinygrad/opsgpu.py", line 158, in forward
    return binary_op(ctx, 'a*b', x, y)
  File "/home/liam/Documents/oss/env/lib/python3.8/site-packages/tinygrad/opsgpu.py", line 91, in binary_op
    raise Exception("shape mismatch in binop %s: %r %r" % (code, x.shape, y.shape))
Exception: shape mismatch in binop a*b: (3, 2) (1,)
```

I cannot replicate the issue using master branch. I can only assume that this has been resolved. 
```
Tensor <pyopencl._cl.Buffer object at 0x7f9f10033860> with grad None
Tensor array([[-0.00388361, -0.00414972],
       [-0.00388361, -0.00414972],
       [-0.00388361, -0.00414972]], dtype=float32) with grad None
Tensor array([[-0.00038836, -0.00041497],
       [-0.00038836, -0.00041497],
       [-0.00038836, -0.00041497]], dtype=float32) with grad None
Tensor <pyopencl._cl.Buffer object at 0x7f9f10026c70> with grad None
Tensor array([[-0.00016901],
       [-0.01124564]], dtype=float32) with grad None
Tensor array([[-1.6901431e-05],
       [-1.1245639e-03]], dtype=float32) with grad None
```

I would recommend, if you wish to use GPU at present,  to install the latest master clone. 
```
git clone git@github.com:geohot/tinygrad.git
cd tinygrad
python setup.py install
```
At least until PyPi is updated.

@geohot I assume PyPi is updated manually?

**Comment by marcelbischoff** [comment]
`.cpu` wasn't working correctly, see #128. Not sure if it is related.
