### ISSUE TITLE
Issue with loss.backwards when running demo code

### ISSUE THREAD

**Issue by PJ-Finlay** [geohot/tinygrad#299]
I'm trying to run the demo code and getting this error:
```
from tinygrad.tensor import Tensor
import tinygrad.optim as optim

class TinyBobNet:
  def __init__(self):
    self.l1 = Tensor.uniform(10, 128)
    self.l2 = Tensor.uniform(128, 10)

  def forward(self, x):
    return x.dot(self.l1).relu().dot(self.l2).logsoftmax()

model = TinyBobNet()
optim = optim.SGD([model.l1, model.l2], lr=0.001)

# ... and complete like pytorch, with (x,y) data
x = Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = Tensor([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

out = model.forward(x)
loss = out.mul(y).mean()
optim.zero_grad()
loss.backward()
optim.step()
```

```
Traceback (most recent call last):
  File "grad.py", line 22, in <module>
    loss.backward()
  File "/home/pj/Desktop/tinygrad/tinygrad/tensor.py", line 131, in backward
    grads = t0._ctx.backward(t0._ctx, t0.grad.data)
  File "/home/pj/Desktop/tinygrad/tinygrad/ops/ops_cpu.py", line 172, in backward
    grad_weight = input.swapaxes(-2, -1) @ grad_output
numpy.AxisError: axis1: axis -2 is out of bounds for array of dimension 1
```

**Comment by Henistein** [comment]
Since you have:
```python
self.l1 = Tensor.uniform(10, 128)
self.l2 = Tensor.uniform(128, 10)
```
Your input must be like this:
```python
x = Tensor([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y = Tensor([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]])
```

**Comment by PJ-Finlay** [comment]
Thanks for the response but this still isn't working for me. With that change I'm getting a different error but on the forward call.
```
from tinygrad.tensor import Tensor
import tinygrad.optim as optim

class TinyBobNet:
  def __init__(self):
    self.l1 = Tensor.uniform(10, 128)
    self.l2 = Tensor.uniform(128, 10)

  def forward(self, x):
    return x.dot(self.l1).relu().dot(self.l2).logsoftmax()

model = TinyBobNet()
optim = optim.SGD([model.l1, model.l2], lr=0.001)

# ... and complete like pytorch, with (x,y) data
x = Tensor([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y = Tensor([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]])

out = model.forward(x)
loss = out.mul(y).mean()
optim.zero_grad()
loss.backward()
optim.step()
```
Output:
```
Traceback (most recent call last):
  File "grad.py", line 19, in <module>
    out = model.forward(x)
  File "grad.py", line 10, in forward
    return x.dot(self.l1).relu().dot(self.l2).logsoftmax()
  File "/home/pj/Desktop/tinygrad/tinygrad/tensor.py", line 210, in matmul
    return self._matmul(w)
  File "/home/pj/Desktop/tinygrad/tinygrad/tensor.py", line 369, in dispatch
    return f.apply(f, *x, **kwargs)
  File "/home/pj/Desktop/tinygrad/tinygrad/tensor.py", line 355, in apply
    po.output = ret = Tensor(self.forward(ctx, *[t.data for t in x], **kwargs),
  File "/home/pj/Desktop/tinygrad/tinygrad/ops/ops_cpu.py", line 167, in forward
    return input @ weight
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 10 is different from 1)
```

**Comment by Henistein** [comment]
I am sorry, my bad, this will work:
```python3
x = Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
y = Tensor([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]])
```

**Comment by PJ-Finlay** [comment]
That did it thanks!
```
from tinygrad.tensor import Tensor
import tinygrad.optim as optim

class TinyBobNet:
  def __init__(self):
    self.l1 = Tensor.uniform(10, 128)
    self.l2 = Tensor.uniform(128, 10)

  def forward(self, x):
    return x.dot(self.l1).relu().dot(self.l2).logsoftmax()

model = TinyBobNet()
optim = optim.SGD([model.l1, model.l2], lr=0.001)

# ... and complete like pytorch, with (x,y) data
x = Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
y = Tensor([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]])

out = model.forward(x)
loss = out.mul(y).mean()
optim.zero_grad()
loss.backward()
optim.step()
```
