### ISSUE TITLE
invalid syntax: ../../accel/cuda/ops_cuda.py

### ISSUE THREAD

**Issue by nilday** [geohot/tinygrad#313]
from tinygrad.tensor import Tensor
returns error:

Traceback (most recent call last):
  File "E:\workspace\python\tinygrad_test\main.py", line 5, in <module>
    from tinygrad.tensor import Tensor
  File "e:\workspace\python\tinygrad\tinygrad\__init__.py", line 1, in <module>
    from tinygrad import optim, tensor, nn
  File "e:\workspace\python\tinygrad\tinygrad\optim.py", line 2, in <module>
    from tinygrad.tensor import Tensor
  File "e:\workspace\python\tinygrad\tinygrad\tensor.py", line 416, in <module>
    _register_ops(importlib.import_module('tinygrad.ops.'+ops), d)
  File "C:\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "e:\workspace\python\tinygrad\tinygrad\ops\ops_cuda.py", line 1
    ../../accel/cuda/ops_cuda.py
    ^
SyntaxError: invalid syntax

**Comment by ayushmankumar7** [comment]
I am getting the same error. 
What's the reason behind having just a "directory" in a python file? 

I saw this in both ops_llvm.py and ops_cuda.py.
