### ISSUE TITLE
tensor.py: tuple index out of range

### ISSUE THREAD

**Issue by 0ihsan** [geohot/tinygrad#435]
```
~/c/a/tinygrad ❯ python3 -m examples.stable_diffusion
ops_llvm not available No module named 'llvmlite'
ops_torch not available No module named 'torch'
issue assigning object on 699
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1145/1145 [00:14<00:00, 79.25it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ihsan/c/a/tinygrad/examples/stable_diffusion.py", line 658, in <module>
    context = model.cond_stage_model.transformer.text_model(phrase).realize()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/c/a/tinygrad/examples/stable_diffusion.py", line 485, in __call__
    x = self.embeddings(input_ids, list(range(len(input_ids))))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/c/a/tinygrad/examples/stable_diffusion.py", line 474, in __call__
    inputs_embeds = Tensor(inputs, device=self.token_embedding['weight'].device) @ self.token_embedding['weight']
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/Users/ihsan/c/a/tinygrad/tinygrad/tensor.py", line 198, in matmul
    cx = self.transpose(order=order).reshape(shape=(bs//groups, groups*cin, -1, 1))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/c/a/tinygrad/tinygrad/tensor.py", line 209, in transpose
    def transpose(self, order=(1,0)): return self.permute(order=order)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/c/a/tinygrad/tinygrad/tensor.py", line 307, in permute
    def permute(self, order, *args): return self._permute(order=argfix(order, *args))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/c/a/tinygrad/tinygrad/tensor.py", line 335, in apply
    ctx = cls(x[0].device, *x)
              ~^^^
IndexError: tuple index out of range
```

i am using sd model `v1-5-pruned-emaonly.ckpt` on m1.

**Comment by geohot** [comment]
Wrong weights file, see link in README
