### ISSUE TITLE
Python 3.11 changed classmethod behavior? 

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#475]
```
kafka@quiet:~/fun/tinygrad$ GPU=1 PYTHONPATH="." python3 examples/benchmark_train_efficientnet.py
ops_llvm not available No module named 'llvmlite'
ops_torch not available No module named 'torch'
NUM:2 BS:8 CNT:10
  0%|                                                                                                                                                                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/kafka/fun/tinygrad/examples/benchmark_train_efficientnet.py", line 38, in <module>
    out = model.forward(x_train)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kafka/fun/tinygrad/models/efficientnet.py", line 127, in forward
    x = self._bn0(x.conv2d(self._conv_stem, padding=(0,1,0,1), stride=2)).swish()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kafka/fun/tinygrad/tinygrad/tensor.py", line 258, in conv2d
    ret = self._conv2d(weight, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kafka/fun/tinygrad/tinygrad/tensor.py", line 339, in apply
    ctx = cls(x[0].device, *x)
          ^^^^^^^^^^^^^^^^^^^^
TypeError: 'Tensor' object is not callable
```

Fine in 3.10.9

**Comment by geohot** [comment]
Replaced with lambda to fix
