### ISSUE TITLE
Error when running the First Example

### ISSUE THREAD

**Issue by Raghvender1205** [geohot/tinygrad#579]
Upon installing the latest `tinygrad` module on windows. I am not able to run this example 

```python
from tinygrad.tensor import Tensor

x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0, 0, -2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()

print(x.grad.numpy()) # dz/dx
print(x.grad.numpy()) # dz/dy
```

Python 3.10.9 64 bit

I am getting this error
```
Traceback (most recent call last):
  File "D:\ML_RESEARCH\TinyGrad\Examples\first_example.py", line 1, in <module>
    from tinygrad.tensor import Tensor
  File "d:\ml_research\tinygrad\tinygrad\tinygrad\__init__.py", line 1, in <module>
    from tinygrad import tensor, nn  # noqa: F401
  File "d:\ml_research\tinygrad\tinygrad\tinygrad\tensor.py", line 7, in <module>
    from tinygrad.lazy import Device, LazyBuffer
  File "d:\ml_research\tinygrad\tinygrad\tinygrad\lazy.py", line 31, in <module>
    Device = _Device()
  File "d:\ml_research\tinygrad\tinygrad\tinygrad\lazy.py", line 27, in __init__
    self._buffers[name] = [cls for cname, cls in inspect.getmembers(importlib.import_module('tinygrad.llops.'+op), inspect.isclass) if (cname.upper() == name + "BUFFER")][0]
  File "C:\Users\raghv\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "d:\ml_research\tinygrad\tinygrad\tinygrad\llops\ops_triton.py", line 1
    ../../accel/triton/ops_triton.py
    ^
SyntaxError: invalid syntax
```

**Comment by martinloretzzz** [comment]
The symlinks aren't working on windows, you can delete the tinygrad/llops/ops_triton.py file locally and it should work.

**Comment by Raghvender1205** [comment]
Okay!! Done !! Issue Resolved

**Comment by martinloretzzz** [comment]
Fixed by https://github.com/geohot/tinygrad/pull/584 and https://github.com/geohot/tinygrad/commit/ac8daaeea540f0de8d0af33b44245d7478fee7ab

You should now be able to use the master branch without modifications.
