### ISSUE TITLE
KeyError: dtype('uint8') On running Examples

### ISSUE THREAD

**Issue by ayushmankumar7** [geohot/tinygrad#701]
On running any example, I am getting this error. 
OS: Windows 11 
GPU: Nvidia GTX 1650 
```
$ GPU=1 python examples/efficientnet.py webcam
using <pyopencl.Device 'NVIDIA GeForce GTX 1650' on 'NVIDIA CUDA' at 0x2136340c2c0>
https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/efficientnet-b0-355c32eb.pth: 100%|█| 21.4M/21.4M [00:
https://gist.githubusercontent.com/yrevar/942d3a0ac09ec9e5eb3a/raw/238f720ff059c1f82f368259d1ca4ffa5dd8f9f5/imagenet1000_clsid
Traceback (most recent call last):
  File "F:\OTHER_FUN_Projects\tinygrad\examples\efficientnet.py", line 77, in <module>
    out, retimg = infer(model, img)
  File "F:\OTHER_FUN_Projects\tinygrad\examples\efficientnet.py", line 48, in infer
    out = _infer(model, Tensor(img)).numpy()
  File "f:\other_fun_projects\tinygrad\tinygrad\tensor.py", line 45, in __init__
    lazydata = LazyBuffer.fromCPU(data.astype(dtype.np) if dtype is not None else data, device)
  File "f:\other_fun_projects\tinygrad\tinygrad\lazy.py", line 154, in fromCPU
    def fromCPU(x, device) -> LazyBuffer: return LazyBuffer(device, x.shape, LoadOps, LazyOp(LoadOps.FROMCPU, tuple(), x.copy()), dtypes.from_np(x))
  File "f:\other_fun_projects\tinygrad\tinygrad\helpers.py", line 42, in from_np
    def from_np(x:Union[LazyNumpyArray, np.ndarray]) -> DType: return {np.dtype(np.float16): dtypes.float16, np.dtype(np.float32): dtypes.float32}[np.dtype(x.dtype)]
KeyError: dtype('uint8')
```

**Comment by jla524** [comment]
This should be fixed now. Please let me know if it works for you

**Comment by ayushmankumar7** [comment]
@jla524 Yes, it works! Thanks for the PR.
