### ISSUE TITLE
LLaMa MEM_OBJECT_ALLOCATION_FAILURE when start

### ISSUE THREAD

**Issue by CoffeeAddictGuy** [geohot/tinygrad#704]
Hi, I'm trying to run LLaMa on 7B scales, but every time I have a memory error of 80 percent with RTX3060
My bat file to run
```
set OPTLOCAL=1
set GPU=2
C:\Users\richc\AppData\Local\Programs\Python\Python310\python.exe examples/llama.py
pause
```
The error I'm getting
```
richardlovescoffee@CAFFEINEPLZ G:\LLaMa\tinygrad
# C:\Users\richc\AppData\Local\Programs\Python\Python310\python.exe examples/llama.py
using GPU backend
loading 260 ram used: 12.08 GB:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 260/323 [03:51<00:56,  1.12it/s] loaded weights in 231498.10 ms, 12.17 GB loaded at 0.05 GB/s
Traceback (most recent call last):
  File "G:\LLaMa\tinygrad\examples\llama.py", line 271, in <module>
    weights = fake_torch_load_zipped(open(WEIGHTS_FILENAME, "rb"), load_weights=getenv("WEIGHTS", 1), base_name="consolidated")
  File "g:\llama\tinygrad\extra\utils.py", line 151, in fake_torch_load_zipped
    load_weight(k,v)
  File "g:\llama\tinygrad\extra\utils.py", line 138, in load_weight
    load_single_weight(v[2], myfile, v[3], v[4], v[0], mmap_allowed=True)
  File "g:\llama\tinygrad\extra\utils.py", line 125, in load_single_weight
    t.realize()
  File "g:\llama\tinygrad\tinygrad\tensor.py", line 83, in realize
    self.lazydata.realize()
  File "g:\llama\tinygrad\tinygrad\lazy.py", line 144, in realize
    self.realized = self.dbuffer.exec_ast(ast, output_buffer=self.output_buffer)
  File "g:\llama\tinygrad\tinygrad\ops.py", line 129, in exec_ast
    if ast.op == LoadOps.FROMCPU: return cls(ast.arg.shape, backing=ast.arg.ravel(), dtype=dtypes.from_np(ast.arg))
  File "g:\llama\tinygrad\tinygrad\ops.py", line 104, in __init__
    if (self._backing is not None and self._backing.shape != (1,)) or force_create: self.raw()
  File "g:\llama\tinygrad\tinygrad\ops.py", line 117, in raw
    self._buf = self.create_raw_buffer(self._base_shape, self._backing, self.dtype)
  File "g:\llama\tinygrad\tinygrad\runtime\ops_gpu.py", line 80, in create_raw_buffer
    else: return super().create_raw_buffer(shape, backing, dtype)
  File "g:\llama\tinygrad\tinygrad\ops.py", line 112, in create_raw_buffer
    return self.spec.raw_buffer(prod(shape), dtype) if backing is None else self.spec.raw_buffer.fromCPU(backing)
  File "g:\llama\tinygrad\tinygrad\runtime\lib.py", line 26, in fromCPU
    ret._copyin(x)
  File "g:\llama\tinygrad\tinygrad\runtime\ops_gpu.py", line 28, in _copyin
    def _copyin(self, x:np.ndarray): cl.enqueue_copy(CL.cl_queue, self._cl, x, is_blocking=False)
  File "C:\Users\richc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyopencl\__init__.py", line 1936, in enqueue_copy
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
pyopencl._cl.MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE
```

Has anyone encountered a problem?

**Comment by geohot** [comment]
Your GPU doesn't have 13GB of RAM
