### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Asory2010** [geohot/tinygrad#718]
using GPU backend
using <pyopencl.Device 'NVIDIA GeForce GTX 1650' on 'NVIDIA CUDA' at 0x2437fb4db30>
loading 72 ram used:  3.67 GB:  22%|███████████▏                                      | 72/323 [00:04<00:13, 17.98it/s]
loaded weights in 4024.53 ms, 3.76 GB loaded at 0.93 GB/s
Traceback (most recent call last):
  File "D:\Ai\tinygrad\examples\llama.py", line 263, in <module>
    weights = fake_torch_load_zipped(open(WEIGHTS_7B_FILENAME, "rb"), load_weights=getenv("WEIGHTS", 1))
  File "d:\ai\tinygrad\extra\utils.py", line 151, in fake_torch_load_zipped
    load_weight(k,v)
  File "d:\ai\tinygrad\extra\utils.py", line 138, in load_weight
    load_single_weight(v[2], myfile, v[3], v[4], v[0], v[5], mmap_allowed=True)
  File "d:\ai\tinygrad\extra\utils.py", line 124, in load_single_weight
    t.realize()
  File "d:\ai\tinygrad\tinygrad\tensor.py", line 88, in realize
    self.lazydata.realize()
  File "d:\ai\tinygrad\tinygrad\lazy.py", line 114, in realize
    self.realized = Device[self.device].buffer.fromCPU(self.op.arg())
  File "d:\ai\tinygrad\tinygrad\runtime\lib.py", line 28, in fromCPU
    ret._copyin(x)
  File "d:\ai\tinygrad\tinygrad\runtime\ops_gpu.py", line 37, in _copyin
    cl.enqueue_copy(CL.cl_queue, self._buf, x, is_blocking=False)
  File "C:\Users\Asser\miniconda3\lib\site-packages\pyopencl\__init__.py", line 1936, in enqueue_copy
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
pyopencl._cl.MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE

**Comment by croumegous** [comment]
This is because you are getting out of memory. You need at least ~14GB of RAM to run LLaMa your GPU have only 4GB VRAM.

**Comment by Asory2010** [comment]
is there a way i can run it with 4gb (i do not care about preformance all that much)

**Comment by croumegous** [comment]
You may try to run it on CPU if you have enough RAM. You can try running `CPU=1 python llama.py` not sure if it is supposed to work well and might be really really really slow.   
If you are only concerned about running LLaMa you might prefer to simply use https://github.com/ggerganov/llama.cpp. For now, this is the best way to do inference on LLaMa with very good performance, and very easy to use.

**Comment by Asory2010** [comment]
ok, thanks

**Comment by Asory2010** [comment]
@croumegous is there maby a way i could use the gpu but with the normal ram not the gpu ram?

**Comment by geohot** [comment]
I'll leave this open. You should be able to hot swap into the GPU, but it will take some work.
