### ISSUE TITLE
examples/stable_diffusion exception on first run

### ISSUE THREAD

**Issue by rweichler** [geohot/tinygrad#834]
race condition maybe?

```
tinygrad$ PYTHONPATH="." CLANG=1 python3 examples/stable_diffusion.py
https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.27G/4.27G [35:44<00:00, 1.99MB/s]
loading 1144 ram used:  4.26 GB: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1144/1145 [00:03<00:00, 367.86it/s]
Traceback (most recent call last):
  File "examples/stable_diffusion.py", line 620, in <module>
    dat = fake_torch_load_zipped(open(FILENAME, "rb"))
  File "/Users/reed/code/gh/geohot/tinygrad/extra/utils.py", line 146, in fake_torch_load_zipped
    if future.exception() is not None: raise future.exception()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/reed/code/gh/geohot/tinygrad/extra/utils.py", line 139, in load_weight
    load_single_weight(v[2], myfile, v[3], v[4], v[0], v[5], mmap_allowed=True)
  File "/Users/reed/code/gh/geohot/tinygrad/extra/utils.py", line 114, in load_single_weight
    myfile.readinto(t.lazydata.realized._buffer())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1030, in _read1
    self._update_crc(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 958, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'archive/data/1143'
```

running it a second time works just fine:

```
ttinygrad$ PYTHONPATH="." CLANG=1 python3 examples/stable_diffusion.py
loading 1139 ram used:  4.26 GB: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1145/1145 [00:02<00:00, 411.73it/s]
got CLIP context (1, 77, 768)
got unconditional CLIP context (1, 77, 768)
running for [1, 201, 401, 601, 801] timesteps
  0   1: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [08:20<00:00, 100.08s/it]
decode (1, 512, 64, 64)
decode (1, 512, 128, 128)
decode (1, 512, 256, 256)
decode (1, 256, 512, 512)
(512, 512, 3)
saving /tmp/rendered.png
 ```

**Comment by python273** [comment]
what OS?

Also check shasum just in case
```
$ shasum weights/sd-v1-4.ckpt
210783247af4f65a3d23d026490cc37a670964dd  weights/sd-v1-4.ckpt
```

**Comment by rweichler** [comment]
macOS arm64. shasum matches.

i think you misread my post. i dont need help. it seems like there's a race condition on the first run.

**Comment by geohot** [comment]
The new torch loader should help with this.

**Comment by geohot** [comment]
Should be fixed with DiskTensors
