### ISSUE TITLE
Intermittent segfault on M1 Mac running on `METAL` with `test_maxpool2d`

### ISSUE THREAD

**Issue by kposborne2** [geohot/tinygrad#931]
Using git bisect, it seems to be introduced by this commit: f2a964f4472cf11be354f38b5e681f1fa50086c8
I believe this is the same issue reported by @jla524 
It has been reproducing reliably by running it repeatedly:
```
pip install pytest-flakefinder
pytest test/test_ops.py::TestOps::test_maxpool2d --flake-finder --flake-runs 1000
```
```
Thread 0x000000029045b000 (most recent call first):
<no Python frame>

Current thread 0x0000000100b8c580 (most recent call first):
  File "/Users/kosborne/.pyenv/versions/tinygrad/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 799 in assert_array_compare
  File "/Users/kosborne/.pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75 in inner
  File "/Users/kosborne/.pyenv/versions/tinygrad/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1592 in assert_allclose
  File "/Users/kosborne/learning/tinygrad/test/test_ops.py", line 34 in compare
  File "/Users/kosborne/learning/tinygrad/test/test_ops.py", line 52 in helper_test_op
  File "/Users/kosborne/learning/tinygrad/test/test_ops.py", line 533 in test_maxpool2d
  File "/Users/kosborne/.pyenv/versions/3.8.12/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/Users/kosborne/.pyenv/versions/3.8.12/lib/python3.8/unittest/case.py", line 676 in run
  File "/Users/kosborne/.pyenv/versions/3.8.12/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/Users/kosborne/.pyenv/versions/tinygrad/lib/python3.8/site-packages/_pytest/unittest.py", line 333 in runtest
  File "/Users/kosborne/.pyenv/versions/tinygrad/lib/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
 ... more test harness boilerplate
```
If I comment out the `.release()` part, the segfault goes away, so I think there is a numpy array referencing the `_buffer`, which got released to cause the problem.
```
class RawMetalBuffer(RawBufferMapped):
  def __init__(self, size:int, dtype:DType): super().__init__(size, dtype, METAL.device.newBufferWithLength_options_(size*dtype.itemsize, Metal.MTLResourceStorageModeShared))
  def __del__(self):
    self._buf.release()
    super().__del__()
  def _buffer(self):
    METAL.synchronize()
    return self._buf.contents().as_buffer(self._buf.length())
```
Someone from the discord suggested setting the `.base` parameter of the ndarray. I think that makes sense, if the numpy array can keep the `RawMetalBuffer` object alive that will work well. However when trying that, I got this problem:
```
>>> arr.base = a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute 'base' of 'numpy.ndarray' objects is not writable
```
I think a workaround to that would be to subclass the numpy array, but that feels not so great: 
https://stackoverflow.com/questions/66744512/adding-arbitrary-extra-attribute-to-numpy-ndarray
https://numpy.org/doc/stable/user/basics.subclassing.html#simple-example-adding-an-extra-attribute-to-ndarray

Another option would be to create the buffer in the python side and share it to metal, because these python objects already track the references correctly. I found this was possible with sending a ctypes array to  
`METAL.device.newBufferWithBytesNoCopy_length_options_deallocator_`, however the buffer must be page-aligned, and it started making tests fail all the time unless I forced all `MetalProgram` calls to wait for their command buffer completion.

**Comment by geohot** [comment]
What if you set an attr on the numpy array?

**Comment by geohot** [comment]
Should be fixed https://github.com/geohot/tinygrad/pull/964
