### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'x86_64'

### ISSUE THREAD

**Issue by hbf731eF** [geohot/tinygrad#945]
```
$ uname
linux

$ python3 -m examples.whisper
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/github/tinygrad/examples/whisper.py", line 9, in <module>
    from extra.utils import download_file
  File "/tmp/github/tinygrad/extra/utils.py", line 8, in <module>
    from tinygrad.tensor import Tensor
  File "/tmp/github/tinygrad/tinygrad/tensor.py", line 7, in <module>
    from tinygrad.lazy import Device, LazyBuffer
  File "/tmp/github/tinygrad/tinygrad/lazy.py", line 329, in <module>
    Device = _Device()
  File "/tmp/github/tinygrad/tinygrad/lazy.py", line 316, in __init__
    self.DEFAULT: str = functools.reduce(lambda val, ele: ele if getenv(ele) == 1 else val, self._buffers, self._default_device())
  File "/tmp/github/tinygrad/tinygrad/lazy.py", line 316, in <lambda>
    self.DEFAULT: str = functools.reduce(lambda val, ele: ele if getenv(ele) == 1 else val, self._buffers, self._default_device())
  File "/tmp/github/tinygrad/tinygrad/helpers.py", line 22, in getenv 
    def getenv(key, default=0): return type(default)(os.getenv(key, str(default)))
ValueError: invalid literal for int() with base 10: 'x86_64'
```

```
diff --git a/tinygrad/helpers.py b/tinygrad/helpers.py
index 450282b..4bdb46d 100644
--- a/tinygrad/helpers.py
+++ b/tinygrad/helpers.py
@@ -18,7 +18,11 @@ def flatten(l:Iterator): return [item for sublist in l for item in sublist]
 def mnum(i) -> str: return str(i) if i >= 0 else f"m{-i}"
 
 @functools.lru_cache(maxsize=None)
-def getenv(key, default=0): return type(default)(os.getenv(key, default))
+def getenv(key, default=0):
+    value = os.getenv(key, str(default))
+    if value == 'x86_64':
+        return value
+    return type(default)(value)
 
 class Context:
   def __init__(self, **kwargs): self.pvars = kwargs
```

**Comment by hbf731eF** [comment]
> 

running without GPU, but CPU=x86_64 and HOSTTYPE=x86_64

**Comment by jla524** [comment]
Okay, try running `CPU=1 python3 -m examples.whisper`.

**Comment by hbf731eF** [comment]
CPU=1 works

in linux 
CPU is probably  derived from `uname -m`

**Comment by cloud11665** [comment]
Check out [docs/env_vars.md](https://github.com/geohot/tinygrad/blob/master/docs/env_vars.md). the CPU env var means that it just runs on the cpu and not the gpu (default)

**Comment by hbf731eF** [comment]
thanks for pointing out the reference. CPU is already set by the linux environment to a value, that cannot be parsed correctly.  the documentation should then clearly state that CPU=1 is mandatory for linux(which would conflict when GPU=1 is set I guess)  or discard the _wrong_ preset value "CPU=x86_64" in the code

**Comment by python273** [comment]
> CPU=1 is mandatory for linux

you can use `CPU=0 GPU=1`. What distro sets CPU env var?

**Comment by hbf731eF** [comment]
CPU=0 works for me

> What distro sets CPU env var?
openSUSE

**Comment by GrahamboJangles** [comment]
I had a similar issue

```
Traceback (most recent call last):
File "E:\Coding_and_Scripting\projects\tinygrad assistant\tinygrad\examples\coder.py", line 60, in
PROMPT = getenv("PROMPT", 1)
File "e:\coding_and_scripting\projects\tinygrad assistant\tinygrad\tinygrad\helpers.py", line 57, in getenv
def getenv(key:str, default=0): return type(default)(os.getenv(key, default))
ValueError: invalid literal for int() with base 10: '(tinyassistant) $P$G'
```

And I fixed it by changing line 56 in .\tinygrad\helpers.py

```python
def getenv(key:str, default=0): return type(default)(os.getenv(key, default))
```
to this:

```python
def getenv(key, default=0):
    value = os.getenv(key, str(default))
    if value == 'x86_64':
        return value
    return type(default)(value)
```
