### ISSUE TITLE
there seems to be an issue with ops_disk.py

### ISSUE THREAD

**Issue by float22** [geohot/tinygrad#957]
Hello, sorry to bother you all here, I don't know if I should ask for help here, but I am having some issues when trying to use the llama weights with llama.py. Here is the error I am getting:

```E:\ai\tinygrad>python llama.py
using GPU backend
Traceback (most recent call last):
  File "E:\ai\tinygrad\llama.py", line 271, in <module>
    load_state_dict(model, torch_load(WEIGHTS_7B_FILENAME), strict=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\state.py", line 95, in torch_load
    if tuple(t[0:2].numpy()) == (0x50, 0x4b):
             ^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\tensor.py", line 103, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\lazy.py", line 193, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\lazy.py", line 115, in realize
    realized = self.op.src[0].realize().realized
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\lazy.py", line 151, in realize
    for x in get_buffers(self.op): x.realize()
                                   ^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\lazy.py", line 136, in realize
    self.realized = Device[self.device].buffer(prod(self.shape), self.dtype, **self._device_extra_args())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\tinygrad\tinygrad\runtime\ops_disk.py", line 14, in __init__
    f = open(device, "a+b")
        ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'E:\\ai\\weights\\LLaMA\\7B\\consolidated.00.pth'
Exception ignored in: <function RawDiskBuffer.__del__ at 0x000002646C328C20>
Traceback (most recent call last):
  File "E:\ai\tinygrad\tinygrad\runtime\ops_disk.py", line 22, in __del__
    self._buf[2] -= 1
    ^^^^^^^^^
AttributeError: 'RawDiskBuffer' object has no attribute '_buf'

**Comment by float22** [comment]
Alright, there was an issue with my windows machine, the app execution aliases for the app installers for python were turned on, which prevented the open() function from working correctly. If anyone else encounters this issue, it can easily be fixed by turning off the app execution aliases for "app installer".
